Repository Develop-Team/DevelopFreedomMod, pull requests merged in 2018-08, with the labels that each got.

#36 Update Command_toggle.java
  src/main/java/me/totalfreedom/totalfreedommod/command/Command_toggle.java
Labels: Bounty PR: Approved, Bounty: Claimed, Bounty: Large, Bug, Bug: Fixed, PR for a Bounty, PR: Accepted, PR: Ready to merge, PR: Waiting for minestone

#34 Allows /deafen to check the list of sounds
  src/main/java/me/totalfreedom/totalfreedommod/command/Command_deafen.java
Labels: Bug, Bug: Fixed, PR: Accepted, PR: Ready to merge, PR: Waiting for minestone, Pull Request

#45 adroition - Request for Project Leadership
  DEVELOPERS.md
Labels: RFA, RFA: Accepted
